### PR TITLE
Update CSDS: Chinese Dataset for Customer Service Dialogue Summarization

### PR DESCRIPTION
**Pull request by xcfcode**
#### Test for `document version`
```
Python 3.8.12 (default, Oct 12 2021, 06:23:56)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from datalabs import load_dataset
>>> dataset = load_dataset("**/Github/DataLab/datasets/csds")
WARNING:datalabs.builder:No config specified, defaulting to: csds_dataset/document
Downloading and preparing dataset csds_dataset/document to **/.cache/expressai/datalab/csds_dataset/document/1.0.0/d917e72cab92a2b631f5495349367fcf2d90d11643ad013711f273f9534a2790...
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████| 61.7M/61.7M [00:22<00:00, 2.70MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████| 5.40M/5.40M [00:01<00:00, 3.41MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████| 5.20M/5.20M [00:07<00:00, 712kB/s]
self.info.dataset_size: None
self.info.download_size: 72298028
Dataset csds_dataset downloaded and prepared to **/.cache/expressai/datalab/csds_dataset/document/1.0.0/d917e72cab92a2b631f5495349367fcf2d90d11643ad013711f273f9534a2790. Subsequent calls will reuse this data.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 853.48it/s]

>>> print(dataset['train']._info)
DatasetInfo(description='In this paper, .......

>>> print(dataset['train']._info.task_templates)
[Summarization(task='summarization', prompts=None, task_category='summarization', text_column='text', summary_column='summary')]

>>> from preprocess import *
>>> res=dataset["test"].apply(lower)
>>> print(next(res))
{'text_lower': 'a:有什么问题我可以帮您处理或解决呢? q:你好 q:以前的手机号码销号了，密码也忘了 q:改密码需要手机验证码 a:还记得您以前的手机号码吗 q:[数字] a:稍等 q:注册邮箱[邮箱] a:若晨[数字] a:是这个用户名吗 q:嗯嗯 a:这边帮您升级专员会在明天[数字]点前给您回电方便提供下您要绑定的手机号码吗 q:[数字] q:其实个人觉得通过注册邮箱验证挺方便的 a:已经为您反馈专员，请您保持电话畅通哦，会尽快联系您的呢 a:请问还有其他还可以帮到您的吗? q:好的，没了，谢谢 a:妹子怠慢的地方，您多多包含哦，辛苦您点击聊天框中的[站点]给我一个评价哦，妹子期待再次为您服务 a:亲请问还有什么我能帮助到您的呢 q:你好，您可以看见我之前反馈的问题吗 a:可以的亲 q:嗯，我现在终于想起密码了，登录进来了，但还是要验证我以前的手机号码 a:没事的哦亲 a:我们这边已经帮您反馈专员了 q:不能邮箱改密码就算了，找到密码还必须验证以前的手机号码 q:不验证现在可以买东西吗 a:还请您耐心等待下 q:好吧，这么麻烦，不合理，再见 a:亲这个是要按照流程走的哦也是为您账户安全着想 a:小妹也理解您的着急'}
```
#### Test for `usersumm version`
```
>>> dataset = load_dataset("**/Github/DataLab/datasets/csds","usersumm")
WARNING:datalabs.builder:Reusing dataset csds_dataset (**/.cache/expressai/datalab/csds_dataset/usersumm/1.0.0/a05ba08e5fc41b112fd7d11e6adf5defe7d7f077b1350ace99b2dd0b95e531c6)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 393.81it/s]
>>> print(dataset['train']._info)
DatasetInfo(description='In this paper, ...

>>> print(dataset['train']._info.task_templates)
[DialogSummarization(task='dialog_summarization', prompts=None, task_category='dialog_summarization', text_column='dialogue', summary_column='user_summary')]

>>> dataset["test"]["dialogue"][0]
{'speaker': ['A', 'Q', 'Q', 'Q', 'A', 'Q', 'A', 'Q', 'A', 'A', 'Q', 'A', 'Q', 'Q', 'A', 'A', 'Q', 'A', 'A', 'Q', 'A', 'Q', 'A', 'A', 'Q', 'Q', 'A', 'Q', 'A', 'A'], 'text': ['有什么问题我可以帮您处理或解决呢?', '你好', '以前的手机号码销号了，密码也忘了', '改密码需要手机验证码', '还记得您以前的手机号码吗', '[数字]', '稍等', '注册邮箱[邮箱]', '若晨[数字]', '是这个用户名吗', '嗯嗯', '这边帮您升级专员会在明天[数字]点前给您回电方便提供下您要绑定的手机号码吗', '[数字]', '其实个人觉得通过注册邮箱验证挺方便的', '已经为您反馈专员，请您保持电话畅通哦，会尽快联系您的呢', '请问还有其他还可以帮到您的吗?', '好的，没了，谢谢', '妹子怠慢的地方，您多多包含哦，辛苦您点击聊天框中的[站点]给我一个评价哦，妹子期待再次为您服务', '亲请问还有什么我能帮助到您的呢', '你好，您可以看见我之前反馈的问题吗', '可以的亲', '嗯，我现在终于想起密码了，登录进来了，但还是要验证我以前的手机号码', '没事的哦亲', '我们这边已经帮您反馈专员了', '不能邮箱改密码就算了，找到密码还必须验证以前的手机号码', '不验证现在可以买东西吗', '还请您耐心等待下', '好吧，这么麻烦，不合理，再见', '亲这个是要按照流程走的哦也是为您账户安全着想', '小妹也理解您的着急']}

>>> dataset["test"]["summary"][0]
['用户询问改密码除手机验证外的其他方法。', '用户询问密码登录后，怎样可以不用手机号验证。', '用户询问不验证是否可以买东西。']
```
#### Test for `agentsumm version`
```
>>> dataset = load_dataset("**/Github/DataLab/datasets/csds","agentsumm")
Downloading and preparing dataset csds_dataset/agentsumm to **/.cache/expressai/datalab/csds_dataset/agentsumm/1.0.0/a05ba08e5fc41b112fd7d11e6adf5defe7d7f077b1350ace99b2dd0b95e531c6...
self.info.dataset_size: None
self.info.download_size: 72298028
Dataset csds_dataset downloaded and prepared to **/.cache/expressai/datalab/csds_dataset/agentsumm/1.0.0/a05ba08e5fc41b112fd7d11e6adf5defe7d7f077b1350ace99b2dd0b95e531c6. Subsequent calls will reuse this data.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 754.28it/s]
>>> print(dataset['train']._info)
DatasetInfo(description='In this paper, ....

>>> print(dataset['train']._info.task_templates)
[DialogSummarization(task='dialog_summarization', prompts=None, task_category='dialog_summarization', text_column='dialogue', summary_column='agent_summary')]

>>> dataset["test"]["dialogue"][0]
{'speaker': ['A', 'Q', 'Q', 'Q', 'A', 'Q', 'A', 'Q', 'A', 'A', 'Q', 'A', 'Q', 'Q', 'A', 'A', 'Q', 'A', 'A', 'Q', 'A', 'Q', 'A', 'A', 'Q', 'Q', 'A', 'Q', 'A', 'A'], 'text': ['有什么问题我可以帮您处理或解决呢?', '你好', '以前的手机号码销号了，密码也忘了', '改密码需要手机验证码', '还记得您以前的手机号码吗', '[数字]', '稍等', '注册邮箱[邮箱]', '若晨[数字]', '是这个用户名吗', '嗯嗯', '这边帮您升级专员会在明天[数字]点前给您回电方便提供下您要绑定的手机号码吗', '[数字]', '其实个人觉得通过注册邮箱验证挺方便的', '已经为您反馈专员，请您保持电话畅通哦，会尽快联系您的呢', '请问还有其他还可以帮到您的吗?', '好的，没了，谢谢', '妹子怠慢的地方，您多多包含哦，辛苦您点击聊天框中的[站点]给我一个评价哦，妹子期待再次为您服务', '亲请问还有什么我能帮助到您的呢', '你好，您可以看见我之前反馈的问题吗', '可以的亲', '嗯，我现在终于想起密码了，登录进来了，但还是要验证我以前的手机号码', '没事的哦亲', '我们这边已经帮您反馈专员了', '不能邮箱改密码就算了，找到密码还必须验证以前的手机号码', '不验证现在可以买东西吗', '还请您耐心等待下', '好吧，这么麻烦，不合理，再见', '亲这个是要按照流程走的哦也是为您账户安全着想', '小妹也理解您的着急']}

>>> dataset["test"]["summary"][0]
['客服让用户提供号码，交给专员回电解决。', '客服帮助反馈用户的问题给专员。', '客服请用户耐心等待。']
```
#### Test for `finalsumm version`
```
>>> dataset = load_dataset("**/DataLab/datasets/csds","finalsumm")
Downloading and preparing dataset csds_dataset/finalsumm to **/.cache/expressai/datalab/csds_dataset/finalsumm/1.0.0/a05ba08e5fc41b112fd7d11e6adf5defe7d7f077b1350ace99b2dd0b95e531c6...
self.info.dataset_size: None
self.info.download_size: 72298028
Dataset csds_dataset downloaded and prepared to **/.cache/expressai/datalab/csds_dataset/finalsumm/1.0.0/a05ba08e5fc41b112fd7d11e6adf5defe7d7f077b1350ace99b2dd0b95e531c6. Subsequent calls will reuse this data.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 651.05it/s]

>>> dataset["test"]["dialogue"][0]
{'speaker': ['A', 'Q', 'Q', 'Q', 'A', 'Q', 'A', 'Q', 'A', 'A', 'Q', 'A', 'Q', 'Q', 'A', 'A', 'Q', 'A', 'A', 'Q', 'A', 'Q', 'A', 'A', 'Q', 'Q', 'A', 'Q', 'A', 'A'], 'text': ['有什么问题我可以帮您处理或解决呢?', '你好', '以前的手机号码销号了，密码也忘了', '改密码需要手机验证码', '还记得您以前的手机号码吗', '[数字]', '稍等', '注册邮箱[邮箱]', '若晨[数字]', '是这个用户名吗', '嗯嗯', '这边帮您升级专员会在明天[数字]点前给您回电方便提供下您要绑定的手机号码吗', '[数字]', '其实个人觉得通过注册邮箱验证挺方便的', '已经为您反馈专员，请您保持电话畅通哦，会尽快联系您的呢', '请问还有其他还可以帮到您的吗?', '好的，没了，谢谢', '妹子怠慢的地方，您多多包含哦，辛苦您点击聊天框中的[站点]给我一个评价哦，妹子期待再次为您服务', '亲请问还有什么我能帮助到您的呢', '你好，您可以看见我之前反馈的问题吗', '可以的亲', '嗯，我现在终于想起密码了，登录进来了，但还是要验证我以前的手机号码', '没事的哦亲', '我们这边已经帮您反馈专员了', '不能邮箱改密码就算了，找到密码还必须验证以前的手机号码', '不验证现在可以买东西吗', '还请您耐心等待下', '好吧，这么麻烦，不合理，再见', '亲这个是要按照流程走的哦也是为您账户安全着想', '小妹也理解您的着急']}

>>> dataset["test"]["summary"][0]
['用户询问改密码除手机验证外的其他方法。', '客服让用户提供号码，交给专员回电解决。', '用户询问密码登录后，怎样可以不用手机号验证。', '客服帮助反馈给专员。', '用户询问不验证是否可以买东西。', '客服请用户耐心等待。']
```

### CODE REVIEW

**Comment by pfliu-nlp** [comment]
@xcfcode thanks for this commit, and this dataset seems pretty valuable!
I noticed that the type of `summary` in `agentsumm version` is a list, I wonder how we usually use it in the training process, for example, 
we can concatenate all summary sentences, which will be regarded as a target text to be generated.

**Comment by pfliu-nlp** [comment]
I will merge this PR, it would be nice if you can also keep this [doc](https://github.com/ExpressAI/DataLab/blob/main/docs/SDK/task_normalization.md) updated every time you add a new dataset.

**Comment by xcfcode** [comment]
I will update the [doc](https://github.com/ExpressAI/DataLab/blob/main/docs/SDK/task_normalization.md) later and refactor the summary format, currently, I follow the `config` from [here](https://github.com/ExpressAI/DataLab/blob/b6378714d0be84e26767d4867908333d8cbba3dc/datasets/samsum/samsum.py#L101).

**Comment by pfliu-nlp** [comment]
I see and thanks!

**Pull request merged**
