### PR TITLE
Add nusax-mt dataset

### PR DESCRIPTION
**Pull request by SamuelCahyawijaya**
Adding NusaX MT dataset.

The dataset is taken from https://github.com/IndoNLP/nusax/tree/main/datasets/mt

### CODE REVIEW

**Review by pfliu-nlp — APPROVED** [review]
Thanks for adding this dataset! Looks great to me.

**Comment by pfliu-nlp** [comment]
Hi, @SamuelCahyawijaya 
here is a trick just in case you don't realize it, regarding how to add new dataset information into `dataset_info.jsonl`

https://github.com/ExpressAI/DataLab/blob/main/docs/SDK/add_new_datasets_into_sdk.md#5-make-your-datasets-registered

**Comment by SamuelCahyawijaya** [comment]
Hi @pfliu-nlp, thank you for noticing. Yeah, I missed this one before. I added the lines on the `dataset_info.jsonl` using another script. Do I need to make any adjustments on the `dataset_info.jsonl` for this dataset?

**Comment by pfliu-nlp** [comment]
Hi @SamuelCahyawijaya it would be nice if you could re-generate the dataset_info.jsonl and make a new PR, since the previous one you made unfortunately involves some format issue, for example: 

image

(each line should be a `{...}`)

**Pull request merged**
