### PR TITLE
[WIP] Rethink/refactoring/normalize task typology

### PR DESCRIPTION
**Pull request by pfliu-nlp**
huge refactoring for task typology, which leads to 100+ dataset loader scripts being updated one by one manually. In summary,
* adopt hierarchical task typology, for example, [1](https://github.com/ExpressAI/DataLab/blob/8f12953a03a6928099ae00b88c5c5491fd61d7cc/datalabs/tasks/summarization.py#L68) (each node in the tree could be regarded as a task, whose parent nodes are recorded by `task_categoreis`, which means each task may have multiple task categories.
* new task schemas are easier to introduce, two steps:
    * define task name:enum: [example](https://github.com/ExpressAI/DataLab/blob/8f12953a03a6928099ae00b88c5c5491fd61d7cc/datalabs/tasks/base.py#L26)
    * define task class:TaskTemplate: [example](https://github.com/ExpressAI/DataLab/blob/8f12953a03a6928099ae00b88c5c5491fd61d7cc/datalabs/tasks/text_classification.py#L48)
* task names are consistent with ExplainaBoard's, by merging these two PRs
    * this PR
    * https://github.com/neulab/ExplainaBoard/pull/303
* almost fix all invalid download links
    * relevant issues: https://github.com/ExpressAI/DataLab/issues/173
* fix some bugs on `task_templates`

Some follow-up things that should be done:
* IMPORTANT:  update `get_dataset_info.py` and `dataset_info.json`
* update docs for newly-introduced task schema.
* make sure all datasets include
    * languages
    * other important metadata
* add task schema for  (also think about modality-dependent schema) 
    * `glue-stsb`
    * `superglue`
    * `polyprompt`
* reformat the organization of some datasets
    * `adv_mtl`
* add unit test for checking the validity of newly-introduced script of dataset loader.

### CODE REVIEW

**Comment by pfliu-nlp** [comment]
# Dataset Update
- [x] adv_mtl
- [x] aeslc 
    * fix error
- [x] afqmc
- [x] ag_news
- [x] ai2_arc
    * fix error

**Comment by pfliu-nlp** [comment]
- [ ] amazon_polarity
    * update invalid download link
    * update `task_templates`

**Comment by pfliu-nlp** [comment]
- [ ] masakhaner
    * update `task_templates`
- [ ] mconala
    * update `task_templates`
- [ ] mlgsum
    * update `task_templates`
- [ ] mlqa
    * update `task_templates`
- [ ] mr
    * update `task_templates`
- [ ] msr
    * update `task_templates` 
- [ ] multi_nli
    * update `task_templates`
- [ ] multi_xscience
    * update `task_templates`
- [ ] multinews
    * update `task_templates`
- [ ] natural_questions
    * update `task_templates` 
- [ ] ncls
    * update `task_templates`
- [ ] nctb
    * update `task_templates`
- [ ] nlpcc14_sc
    * update `task_templates`
- [ ] onlineshopping
    * update `task_templates` 
- [ ] ontonotes_ner
    * update `task_templates`
- [ ] open4business
    * update `task_templates`
- [ ] openbookqa
    * update `task_templates`
- [ ] peersum
    * update `task_templates` 
- [ ] piqa
    * update `task_templates`
- [ ] pn_summary
    * update `task_templates`
- [ ] poem_sentiment
    * update `task_templates`
- [ ] poly_prompt
    * update `task_templates` 
- [ ] pts
    * update `task_templates`
- [ ] pubmed_sum
    * update `task_templates`
- [ ] qasc
    * update `task_templates`
- [ ] qbsum
    * update `task_templates` 
- [ ] qc
    * update `task_templates`
- [ ] qmsum
    * update `task_templates`
- [ ] quoref
    * update `task_templates`
- [ ] race
    * update `task_templates` 
- [ ] reddit_tifu
    * update `task_templates`
- [ ] restaurant14
    * update `task_templates`
- [ ] restaurant16
    * update `task_templates`
- [ ] ropes
    * update `task_templates` 
- [ ] samsum
    * update `task_templates` 
- [ ] scinli
    * update `task_templates` 
- [ ] scitldr
    * update `task_templates` 
- [ ] se_absa16_cname
    * update `task_templates` 
- [ ] se_absa16_phns
    * update `task_templates` 
- [ ] sick
    * update `task_templates` 
- [ ] sms_spam
    * update `task_templates` 
- [ ] snli
    * update `task_templates` 
- [ ] social_i_qa
    * update `task_templates` 
- [ ] spider
    * update `task_templates` 
- [ ] squad
    * update `task_templates` 
- [ ] squad_adversarial
    * update `task_templates` 
- [ ] squad_v2
    * update `task_templates` 
- [ ] ssn
    * update `task_templates` 
- [ ] sst2
    * update `task_templates` 
- [ ] sst5
    * update `task_templates` 
- [ ] subj
    * update `task_templates` 
- [ ] summscreen
    * update `task_templates` 
- [ ] super_glue
    * update `task_templates` 
- [ ] tnews
    * update `task_templates` 
- [ ] trivia_qa
    * update `task_templates` 
- [ ] tweet_eval
    * update `task_templates` 
- [ ] tweets_hate_speech_detection
    * update `task_templates` 
- [ ] twitter
    * update `task_templates` 
- [ ] tydiqa
    * update `task_templates` 
- [ ] waimai
    * update `task_templates` 
- [ ] wcm2
    * update `task_templates` 
- [ ] weibo_4moods
    * update `task_templates` 
- [ ] weibo_senti
    * update `task_templates` 
- [ ] wiki_hop
    * update `task_templates` 
- [ ] wikihow
    * update `task_templates` 
- [ ] wikilingua
    * update `task_templates` 
- [ ] wikisum
    * update `task_templates` 
- [ ] winogrande
    * update `task_templates` 
- [ ] wmt14
    * update `task_templates` 
- [ ] wmt15
    * update `task_templates` 
- [ ] wmt16
    * update `task_templates` 
- [ ] wmt17
    * update `task_templates` 
- [ ] wmt18
    * update `task_templates` 
- [ ] wmt19
    * update `task_templates` 
- [ ] wmt20_metrics
    * update `task_templates` 
- [ ] wnut_17
    * update `task_templates` 
- [ ] xlsum
    * update `task_templates` 
- [ ] xsum
    * update `task_templates` 
- [ ] xquad
    * update `task_templates` 
- [ ] yahoo_answers_topics
    * update `task_templates` 
- [ ] yelp_review_full
    * update `task_templates` 
- [ ] yf_amazon
    * update `task_templates`

**Review by neubig — APPROVED** [review]
Looks great, I think this PR was a lot of work but it'll be nice to have a more well-defined type hierarchy.

There might be little things we want to adjust later, but I think we can handle them as they become necessary.

**Pull request merged**
